CONTIKI_PROJECT = sky-shell
all: $(CONTIKI_PROJECT)

APPS = serial-shell powertrace collect-view
CONTIKI=$(shell targetos)/contiki

include $(CONTIKI)/Makefile.include
-include /home/user/nes/testbed-scripts/Makefile.include

