#!/bin/bash
#
# Script to perform an automated backup of my home directory to an
# rsync server
#
BACKUP_SERVER=pi@192.168.200.1:

/usr/bin/rsync -avz  /home/aghiles/Aghiles/Program/gateway/lora/lora_gateway $BACKUP_SERVER
