#!/bin/bash
#
# Script to perform an automated backup of my home directory to an
# rsync server
#
BACKUP_SERVER=djoudi@grenoble.iot-lab.info:

/usr/bin/rsync -avz --exclude 'iot-lab/parts/mbed-os' /home/aghiles/Aghiles/Program/boards/ $BACKUP_SERVER


